var mongoose = require('mongoose');
var Exhibitor = new mongoose.Schema({
    No: Number,
    COMPANY_NAME: {type:String, default:''},
    PERSON_NAME: {type:String, default:''},
    EMAIL: {type:String, default:''},
    ALTERNATE_EMAIL: {type:String, default:''},
    membertype:{type:String, default:''},
    TELEPHONE:{type:String, default:''},
    MOBILE:{type:String, default:''},
    ADDRESS1:{type:String, default:''},
    ADDRESS2:{type:String, default:''},
    ADDRESS3:{type:String, default:''},
    COUNTRY:{type:String, default:''},
    STATE:{type:String, default:''},
    CITY:{type:String, default:''},
    REGION:{type:String, default:''},
    PINCODE:{type:String, default:''},
    ORDER_INVOICE_NO:{type:String, default:''},
    TAX_INVOICE_NO:{type:String, default:''},
    BOOK_STALL_DATE:{type:String, default:''},
    STALL_RATE_PER_SQM:{type:String, default:''},
    TOTAL_PRICE:{type:String, default:''},
    FORTYPERCENT:{type:String, default:''},
    SERVICETAX:{type:String, default:''},
    SWACHHBHARATTAX:{type:String, default:''},
    KRISHIKALYANTAX:{type:String, default:''},
    GRANDTOTAL:{type:String, default:''},
    Payment_Mode:{type:String, default:''},
    UTR_TRANSACTION:{type:String, default:''},
    BANK_NAME:{type:String, default:''},
    BRANCH_NAME:{type:String, default:''},
    PAYMENT_MODE:{type:String, default:''},
    PAYMENT_AMOUNT:{type:String, default:''},
    PAYMENT_TDS:{type:String, default:''},
    PAYMENT_CATEGORY:{type:String, default:''},
    PAYMENT_TOTAL:{type:String, default:''},
    PAYMENT_DESCRIPTION:{type:String, default:''},
    HALL_NO:{type:String, default:''},
    HALLTYPE:{type:String, default:''},
    STALLTYPE:{type:String, default:''},
    OPENSIDE:{type:String, default:''},
    AREA:{type:String, default:''},
    DIMENSION:{type:String, default:''},
    STALL_NO:{type:String, default:''},
    CEO_MD_PARTNER_GENDER:{type:String, default:''},
    CEO_MD_PARTNER_NAME:{type:String, default:''},
    CEO_MD_PARTNER_DESIGNATION:{type:String, default:''},
    CEO_MD_PARTNER_EMAIL:{type:String, default:''},
    CEO_MD_PARTNER_TELEPHONE:{type:String, default:''},
    CEO_MD_PARTNER_MOBILE:{type:String, default:''},
    CEO_MD_PARTNER_FAX:{type:String, default:''},
    Agent_RE_Railway_OTA:{type:String, default:''},
    New_Exhibitors:{type:String, default:''},
    password:{type:String, default:''},
    fav_vistors: [{type:String, default:''}],
    Isfav:{type:String, default:'false'},
    qr_image : {type:String, default:''},
    access_token : {type:String, default:''},
    Sitam_id : {type:String, default:""},
    Lat : {type:String, default:""},
    Lng : {type:String, default:""},
    device : {type:String, default:''},
    os_type : {type:String, default:''},
    device_id :  {type:String, default:''},
    profile_pic : {type:String, default:"/images/Users/default_user.png"},
    Brochure_url : {type:String, default:""},
    OTP : {type:String},
    Is_Verified : {type:Boolean, default:false},
    openfire_gid : {type:String, default:''},
    openfire_password : {type:String, default:''},
    USER_TYPE : {type:String, default:'EXHIBITOR'}

},
    {timestamps:true}
);
Exhibitor.index({COMPANY_NAME: 'text', PERSON_NAME: 'text'});
module.exports = mongoose.model('Exhibitor', Exhibitor);